// This file was generated by Prisma, and assumes you have installed the following:
// npm install --save-dev prisma dotenv
import 'dotenv/config';
import { defineConfig } from 'prisma/config';

const schemaByProvider: Record<string, string> = {
  sqlite: 'prisma/schema.prisma',
  postgresql: 'prisma/schema.postgres.prisma',
};

const provider = (process.env['DATABASE_PROVIDER'] || 'sqlite').toLowerCase();
const schema = schemaByProvider[provider] || schemaByProvider.sqlite;

export default defineConfig({
  schema,
  migrations: {
    path: 'prisma/migrations',
  },
  datasource: {
    url: process.env['DATABASE_URL'],
  },
});
